#pragma once
#include "Agui/KeyEvent.hpp"

namespace agui
{
  /** Generic keyboard input class generated by back ends when they receive a keyboard event. */
  class KeyboardInput
  {
  public:
    KeyboardInput(KeyEvent::KeyboardEventEnum event,
                  KeyEnum key,
                  ExtendedKeyEnum extKey,
                  uint32_t unichar,
                  double timeStamp,
                  bool isAlt,
                  bool isShift,
                  bool isControl,
                  bool isMeta,
                  BackendKeycode keyCode,
                  BackendScancode scanCode)
      : key(key)
      , type(event)
      , extKey(extKey)
      , keyCode(keyCode)
      , scanCode(scanCode)
      , unichar(unichar)
      , timeStamp(timeStamp)
      , isAlt(isAlt)
      , isShift(isShift)
      , isControl(isControl)
      , isMeta(isMeta)
    {}

    KeyEnum key;
    KeyEvent::KeyboardEventEnum type;
    ExtendedKeyEnum extKey;
    BackendKeycode keyCode;
    BackendScancode scanCode;
    uint32_t unichar;
    double timeStamp;

    bool isAlt;
    bool isShift;
    bool isControl;
    bool isMeta;
  };
}
