#pragma once
#include "Agui/MouseEvent.hpp"

namespace agui
{
  /** Generic mouse input class generated by back ends when they receive a mouse event. */
  class MouseInput
  {
  public:
    MouseInput(MouseEvent::Type event,
               MouseButton button,
               int x, int y,
               int wheel,
               double timeStamp,
               bool isAlt,
               bool isShift,
               bool isControl)
      : button(button)
      , x(x)
      , y(y)
      , wheel(wheel)
      , timeStamp(timeStamp)
      , type(event)
      , isAlt(isAlt)
      , isControl(isControl)
      , isShift(isShift)
    {}

    MouseButton button;
    int x;
    int y;
    int wheel;
    double timeStamp;
    MouseEvent::Type type;

    bool isAlt;
    bool isControl;
    bool isShift;
  };
}
